## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - nightly
notifications:
  email: false
git:
  depth: 99999999

matrix:
  allow_failures:
    - julia: nightly

after_success:
  # code coverage report
  - julia -e 'using Pkg;
              cd(Pkg.dir("ConstituencyTrees"));
              Pkg.add("Coverage");
              using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  include:
    # build and deploy the documentation
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

    # run the benchmarks
    - stage: "Benchmarking"
      julia: 1.1
      os: linux
      script:
        - cd benchmarks/nltk
        - julia build.jl
